version: "3"

services:
  viscadnode0:
    container_name: viscadnode0
    image: "viscad/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-viscad.log}
    volumes:
      - ./localnet-setup/node0/viscad:/visca:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  viscadnode1:
    container_name: viscadnode1
    image: "viscad/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-viscad.log}
    volumes:
      - ./localnet-setup/node1/viscad:/visca:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  viscadnode2:
    container_name: viscadnode2
    image: "viscad/node"
    environment:
      - ID=2
      - LOG=${LOG:-viscad.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/viscad:/visca:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  viscadnode3:
    container_name: viscadnode3
    image: "viscad/node"
    environment:
      - ID=3
      - LOG=${LOG:-viscad.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/viscad:/visca:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
